# Generated by Django 4.1.2 on 2022-10-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('company', models.TextField()),
                ('color', models.TextField()),
                ('ram', models.TextField()),
                ('memory', models.TextField()),
                ('price', models.FloatField()),
                ('img_url', models.TextField()),
            ],
        ),
    ]
